---

site_name: "WWT - Cisco DevNet DCAUTO Study Resources"
nav:
  - Home: index.md
  - Getting Started:
    - Study Environment Setup: sections/section_0.md
  - Section 1.0:
    - Section 1.1: sections/section_1_1.md
    - Section 1.2: sections/section_1_2.md
    - Section 1.3: sections/section_1_3.md
    - Section 1.4: sections/section_1_4.md
    - Section 1.5: sections/section_1_5.md
    - Section 1.6: sections/section_1_6.md
  - Section 2.0:
    - Section 2.1: sections/section_2_1.md
    - Section 2.2: sections/section_2_2.md
    - Section 2.3: sections/section_2_3.md
    - Section 2.4: sections/section_2_4.md
    - Section 2.5: sections/section_2_5.md
    - Section 2.6: sections/section_2_6.md
  - Section 3.0:
    - Section 3.1: sections/section_3_1.md
    - Section 3.2: sections/section_3_2.md
    - Section 3.3: sections/section_3_3.md
    - Section 3.4: sections/section_3_4.md
    - Section 3.5: sections/section_3_5.md
  - Section 4.0:
    - Section 4.1: sections/section_4_1.md
    - Section 4.2: sections/section_4_2.md
    - Section 4.3: sections/section_4_3.md
    - Section 4.4: sections/section_4_4.md
    - Section 4.5: sections/section_4_5.md
    - Section 4.6: sections/section_4_6.md

# Repository
repo_name: "wwt/dcauto-study-resources"
repo_url: "https://github.com/wwt/dcauto-study-resources"
edit_uri: ""

# Configuration
theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: img/logo.svg
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - attr_list
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
