---
site_name: "WWT - Cisco DevNet DCAUTO Study Resources"
site_url: "https://wwt.github.io/dcauto-study-resources"
nav:
  - Home:
    - DCAUTO Study Resources: index.md
  - Setup:
    - Development Environment Setup: sections/section_0.md
  - Section 1.0:
    - Network Programmability Foundation: sections/section_1.md
  - Section 2.0:
    - Controller Based Data Center Networking: sections/section_2.md
  - Section 3.0:
    - Data Center Device-Centric Networking: sections/section_3.md
  - Section 4.0:
    - Data Center Compute: sections/section_4.md
  - Appendix A:
    - Supplimentary Content: sections/appendix_a.md
  - Appendix B:
    - Jupyter Lab: sections/appendix_b.md

# Repository
repo_name: "wwt/dcauto-study-resources"
repo_url: "https://github.com/wwt/dcauto-study-resources"
edit_uri: ""

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  language: en
  features:
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: img/logo.svg
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  plugins:
    - search:
        prebuild_index: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
