# Sample NX-OS Ansible Host Variables File
---
ansible_host: 192.168.2.109
ansible_network_os: nxos
legacy_os_image: nxos.7.0.3.I7.3.bin
new_os_target_version: 9.3(2)
new_os_image: nxos.9.3.2.bin
new_os_image_checksum: c84203e5bd39c1add7e4119338f75ef2d5934c19
openconfig_rpm: mtx-openconfig-all-1.0.0.0-9.3.2.lib32_n9000.rpm
